name: ScoreQuery

on:
    watch:
        types: started
    schedule:
        # runs every 10 minutes
        - cron: '0/10 * * * *'
        
jobs:
    ScoreQuery:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@master
          - name: Install python3
            run: |
              sudo -E apt-get -yqq update
              sudo -E apt-get -yqq install python3
              sudo pip install lxml
              sudo pip install pandas
              sudo pip install pycryptodome
          - name: Query
            env:
              ACCOUNT: ${{ secrets.ACCOUNT }}
              PASSWORD: ${{ secrets.PASSWORD }}
              MAILTO: ${{ secrets.MAILTO }}
              MAILFROM: ${{ secrets.MAILFROM }}
              KEY: ${{ secrets.KEY }}
            run: |
              python3 scoreQuery.py ${ACCOUNT} ${PASSWORD} ${MAILTO} ${MAILFROM} ${KEY}
          - name: Commit files
            id: commit
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "github-actions"
              git add --all
              if [ -z "$(git status --porcelain)" ]; then
                 echo "::set-output name=push::false"
              else
                 git commit -m "Add changes" -a
                 echo "::set-output name=push::true"
              fi
            shell: bash
          - name: Push changes
            if: steps.commit.outputs.push == 'true'
            uses: ad-m/github-push-action@master
            with:
               github_token: ${{ secrets.TOKEN }}